trees = [
    {
        "name": "White Oak",
        "leaf_type": "simple",
        "leaf_number":"1",
        "leaf_shape": "lobed",
        "leaf_size": "large",
        "leaf_color": "green",
        "leaf_edge": ["deeply lobed","smooth","serrated"],
        "venation": "pinnate",
        "texture": "rough",
        "leaf_autum": ["red","brown"],
        "description": "White Oak (Quercus alba) is a large, long-lived hardwood tree with deeply lobed leaves and a strong, straight trunk. It grows in a variety of habitats and its leaves turn red or brown in autumn. The wood is highly valued for furniture and flooring."
    },
    {
        "name": "Red Oak",
        "leaf_type": "simple",
        "leaf_number":"1",
        "leaf_shape": "lobed",
        "leaf_size": "large",
        "leaf_color": "green",
        "leaf_edge": ["sharp","serrated"],
        "venation": "pinnate",
        "texture": "rough",
        "leaf_autum": ["red"],
        "description": "Red Oak (Quercus rubra) is a fast-growing hardwood tree with pointed, sharply lobed leaves. It's commonly found in upland forests and turns bright red in fall. Its wood is used in construction and cabinetry."
    },
    {
        "name": "Red Maple",
        "leaf_type":"simple",
        "leaf_number":"1",
        "leaf_shape": "palmate",
        "leaf_size": "medium",
        "leaf_color": "green",
        "leaf_edge": "serrated",
        "venation": "palmate",
        "texture": "smooth",
        "leaf_autum": ["red","yellow"],
        "description": "Red Maple (Acer rubrum) is one of the most widespread trees in eastern North America. It has palmate leaves that turn vibrant red or yellow in autumn. It thrives in a wide range of soil types and is often planted for its ornamental value."
    },
    {
        "name": "Sugar Maple",
        "leaf_type":"simple",
        "leaf_number":"1",
        "leaf_shape": "palmate",
        "leaf_size": ["medium","large"],
        "leaf_color": "green",
        "leaf_edge": "serrated",
        "venation": "palmate",
        "texture": "smooth",
        "leaf_autum": ["red","orange","yellow"],
        "description": "Sugar Maple (Acer saccharum) is famous for its brilliant fall foliage—ranging from orange to red—and for being the primary source of maple syrup. It prefers moist, well-drained soils and can grow quite large."
    },
    {
        "name": "Birch",
        "leaf_type": "simple",
        "leaf_number": "1",
        "leaf_shape": ["oval","diamond"],
        "leaf_size": ["small","medium"],
        "leaf_color": "yellow",
        "leaf_edge": "serrated",
        "venation": "pinnate",
        "texture": "smooth",
        "leaf_autum": "yellow",
        "description": "Birch trees (Betula spp.) are medium-sized trees with smooth, often peeling bark and diamond or oval-shaped leaves. In Virginia, Yellow and River Birch are most common. Leaves are serrated and turn yellow in fall."
    },
    {
        "name": "Tulip Poplar",
        "leaf_type": "simple",
        "leaf_number": "1",
        "leaf_shape": "lobed",
        "leaf_size": "large",
        "leaf_color": "green",
        "leaf_edge": "smooth",
        "venation": "pinnate",
        "texture": "smooth",
        "leaf_autum": "yellow",
        "description": "Tulip Poplar (Liriodendron tulipifera) is one of the tallest native trees in Virginia. It has large, uniquely shaped leaves and greenish-yellow tulip-like flowers in spring. Leaves turn bright yellow in fall."
    },
    {
        "name": "Eastern Hemlock",
        "leaf_type":"compound",
        "leaf_shape": "needles",
        "leaf_number":["10","11","12","13","14","15","16","17","18","19","20"],
        "leaf_size": "small",
        "leaf_color": "green",
        "leaf_edge": "smooth",
        "venation": "parallel",
        "texture": "smooth",
        "leaf_autum": "evergreen",
        "description": "Eastern Hemlock (Tsuga canadensis) is an evergreen conifer with short, flat needles and drooping branches. It prefers cool, shady areas and moist soils, often found in ravines and along streams."
    },
    {
        "name": "American Beech",
        "leaf_type":"compound",
        "leaf_number":["7","8","9","10","11","12","13","14","15","16","17","18","19"],
        "leaf_shape": ["oval","elliptical"],
        "leaf_size": "medium",
        "leaf_color": "green",
        "leaf_edge": "serrated",
        "venation": "pinnate",
        "texture": "smooth",
        "leaf_autum": ["yellow","orange","copper"],
        "description": "American Beech (Fagus grandifolia) has smooth, gray bark and toothed, elliptical leaves that turn copper or golden-yellow in autumn. It forms dense shade and grows slowly but steadily in rich woodlands."
    },
    {
        "name": "Black Cherry",
        "leaf_type":"simple",
        "leaf_number":"1",
        "leaf_shape": "elliptical",
        "leaf_size": "medium",
        "leaf_color": "green",
        "leaf_edge": "serrated",
        "venation": "pinnate",
        "texture": "smooth",
        "leaf_autum": ["yellow","orange"],
        "description": "Black Cherry (Prunus serotina) is a medium-sized tree with glossy, serrated leaves and dark, flaky bark. In spring, it produces clusters of white flowers, followed by small, dark fruits. Its wood is prized in fine woodworking."
    },
    {
        "name": "White Pine",
        "leaf_type": "compound",
        "leaf_number":"5",
        "leaf_shape": "needles",
        "leaf_size": "large",
        "leaf_color": "green",
        "leaf_edge": "smooth",
        "venation": "parallel",
        "texture": "smooth",
        "leaf_autum": "evergreen",
        "description": "White Pine (Pinus strobus) is a tall, straight conifer with soft, flexible needles grouped in clusters of five. It grows fast and is used extensively for lumber. It remains green year-round and is found in cool, dry sites."
    },
    {
        "name": "Black Walnut",
        "leaf_type": "compound",
        "leaf_number":["9","10","11","12","13","14","15","16","17","18","19","20","21"],
        "leaf_shape": "elliptical",
        "leaf_size": "large",
        "leaf_color": "green",
        "leaf_edge": "serrated",
        "venation": "pinnate",
        "texture": "smooth",
        "leaf_autum": "yellow",
        "description": "Black Walnut (Juglans nigra) is known for its high-quality dark wood and large edible nuts. It has compound leaves and rough bark. Found in rich, moist soils, it’s valued for both wildlife and commercial use."
    },

    {
        "name": "American Sycamore",
        "leaf_type": "simple",
        "leaf_number": "1",
        "leaf_shape": "palmate",
        "leaf_size": "large",
        "leaf_color": "green",
        "leaf_edge": "lobed",
        "venation": "palmate",
        "texture": "rough",
        "leaf_autum": ["yellow"],
        "description": "American Sycamore (Platanus occidentalis) is a large, fast-growing tree often found near streams and rivers. Its broad, palmate leaves turn yellow in autumn. The tree's bark is distinctive, peeling in large patches to reveal white inner bark."
    },
    {
        "name": "Sweetgum",
        "leaf_type": "simple",
        "leaf_number": "1",
        "leaf_shape": "lobed",
        "leaf_size": "medium",
        "leaf_color": "green",
        "leaf_edge": "lobed",
        "venation": "palmate",
        "texture": "smooth",
        "leaf_autum": ["yellow", "red", "purple"],
        "description": "Sweetgum (Liquidambar styraciflua) is a medium-sized tree known for its star-shaped leaves. In autumn, its leaves turn vibrant shades of yellow, red, and purple. Sweetgum is often found in wet soils and is used for its hardwood in furniture and flooring."
    },
    {
        "name": "White Ash",
        "leaf_type": "compound",
        "leaf_number": ["5", "7", "9"],
        "leaf_shape": "ovate",
        "leaf_size": "medium",
        "leaf_color": "green",
        "leaf_edge": "serrated",
        "venation": "pinnate",
        "texture": "smooth",
        "leaf_autum": ["yellow", "purple"],
        "description": "White Ash (Fraxinus americana) is a tall deciduous tree with compound leaves that turn yellow or purple in the fall. It is commonly used for making baseball bats and furniture. White Ash grows in a variety of soil types, thriving in moist conditions."
    },
    {
        "name": "Pecan",
        "leaf_type": "compound",
        "leaf_number": ["13", "15", "17"],
        "leaf_shape": "lanceolate",
        "leaf_size": "large",
        "leaf_color": "green",
        "leaf_edge": "serrated",
        "venation": "pinnate",
        "texture": "smooth",
        "leaf_autum": ["yellow", "brown"],
        "description": "Pecan (Carya illinoinensis) is a large tree known for its edible nuts and tall, spreading canopy. Its long, lanceolate leaves have serrated edges and turn yellow or brown in autumn. Pecans grow best in deep, moist soils along rivers and floodplains."
    },
    {
        "name": "Black Locust",
        "leaf_type": "compound",
        "leaf_number": ["7", "9", "13"],
        "leaf_shape": "ovate",
        "leaf_size": "medium",
        "leaf_color": "green",
        "leaf_edge": "smooth",
        "venation": "pinnate",
        "texture": "smooth",
        "leaf_autum": "yellow",
        "description": "Black Locust (Robinia pseudoacacia) is a fast-growing, medium-sized tree with compound leaves and fragrant white flowers in spring. Its leaves turn yellow in autumn. The wood is durable and often used for fence posts, and the tree is commonly found in disturbed habitats."
    },
    {
        "name": "Redbud",
        "leaf_type": "simple",
        "leaf_number": "1",
        "leaf_shape": "heart-shaped",
        "leaf_size": "medium",
        "leaf_color": "green",
        "leaf_edge": "smooth",
        "venation": "palmate",
        "texture": "smooth",
        "leaf_autum": "yellow",
        "description": "Redbud (Cercis canadensis) is a small to medium-sized tree, often used for ornamental purposes due to its stunning spring flowers, which range from purple to pink. The heart-shaped leaves turn bright yellow in autumn."
    },
    {
        "name": "Boxelder",
        "leaf_type": "compound",
        "leaf_number": ["3", "5", "7"],
        "leaf_shape": "ovate",
        "leaf_size": "medium",
        "leaf_color": "green",
        "leaf_edge": "smooth",
        "venation": "pinnate",
        "texture": "smooth",
        "leaf_autum": "yellow",
        "description": "Boxelder (Acer negundo) is a small to medium-sized deciduous tree with compound leaves and greenish-yellow flowers in spring. Its leaves turn yellow in the fall, and the tree is commonly found in disturbed sites along rivers or floodplains."
    },
    {
        "name": "Northern Red Oak",
        "leaf_type": "simple",
        "leaf_number": "1",
        "leaf_shape": "lobed",
        "leaf_size": "large",
        "leaf_color": "green",
        "leaf_edge": "sharp",
        "venation": "pinnate",
        "texture": "rough",
        "leaf_autum": ["red", "brown"],
        "description": "Northern Red Oak (Quercus rubra) is a large, fast-growing tree with pointed lobed leaves that turn red or brown in autumn. It is native to the northeastern U.S. but also grows in parts of Virginia. Its wood is widely used for furniture and flooring."
    },
    {
        "name": "Shagbark Hickory",
        "leaf_type": "compound",
        "leaf_number": ["5", "7", "9"],
        "leaf_shape": "ovate",
        "leaf_size": "medium",
        "leaf_color": "green",
        "leaf_edge": "serrated",
        "venation": "pinnate",
        "texture": "rough",
        "leaf_autum": "yellow",
        "description": "Shagbark Hickory (Carya ovata) is a large tree with unique, shaggy bark. Its compound leaves turn yellow in the fall. The nuts are edible and are prized by wildlife. This tree is common in well-drained upland soils."
    },
    {
        "name": "Hornbeam",
        "leaf_type": "simple",
        "leaf_number": "1",
        "leaf_shape": "ovate",
        "leaf_size": "small",
        "leaf_color": "green",
        "leaf_edge": "serrated",
        "venation": "pinnate",
        "texture": "smooth",
        "leaf_autum": ["yellow", "orange"],
        "description": "Hornbeam (Carpinus caroliniana) is a small to medium-sized tree often found in moist woodlands and along streams. It has finely serrated, ovate leaves that turn yellow or orange in the fall. The wood is tough and is used for tool handles and other sturdy items."
    }
]